version: '3'
services:


  java-development:
    image: eventuateio/eventuate-tram-examples-customers-and-orders-java-development:latest
    volumes:
      - .:/eventuate-tram-examples-customers-and-orders
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
